### ISSUE TITLE
Wrong message shown for updateTask command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#107]
**Describe the bug**
After successfully updating the task name, error message shows saying task already exists instead of success.

**To Reproduce**
1. Key in "updateTask 2 n/lab" and enter
2. See error

**Expected behavior**
Command message should be something like "Update successful!"

**Screenshots**
Before:
![screenshot 6](https://user-images.githubusercontent.com/35787585/47905444-24f72b00-dec2-11e8-935c-9598152bf3dd.png)
After:
![screenshot 7](https://user-images.githubusercontent.com/35787585/47905475-3b04eb80-dec2-11e8-9fb7-24534fdbe3ad.png)

**Additional context**
-

<hr>

**Reported by:** @kelvintankaiboon
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#82]</sub>

**Comment by luhan02** [comment]
fixed in #143
