### ISSUE TITLE
expenseTrend command not showing a bar graph

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#109]
**Describe the bug**
No observable and useful data shown when expenseTrend command is executed.
Happens when the expenses in any of the past 6 months is too large.

**To Reproduce**
1. Run the following command
 addExpense c/name v/10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.00 d/02/11/2018 t/hi
OR 
replace the value with any big number
2. Execute the command expenseTrend

**Expected behavior**
expenseTrend Command should display a bar chart showing the last 6 months of expenses
**Screenshots**
![image](https://user-images.githubusercontent.com/35420846/47905993-4573b500-dec3-11e8-83cc-e3d4e4ecef97.png)

<hr>

**Reported by:** @ladderinc
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#201]</sub>

**Comment by ChenSongJian** [comment]
fixed in #130
