### ISSUE TITLE
Can updateTask with invalid date

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#110]
**Describe the bug**
User is allowed to update an invalid date

**To Reproduce**
1. Key in "updateTask 1 s/00/00"
2. See error

**Expected behavior**
An error message should be shown when invalid dates are inputted.

**Screenshots**
![screenshot 8](https://user-images.githubusercontent.com/35787585/47906480-4bb66100-dec4-11e8-8e1c-d03393723338.png)

**Additional context**

<hr>

**Reported by:** @kelvintankaiboon
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#244]</sub>

**Comment by luhan02** [comment]
fixed in #143
