### ISSUE TITLE
Can updateTask with invalid time

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#111]
**Describe the bug**
Can update tasks with invalid times like 2500

**To Reproduce**
1. Key in "updateTask 1 s/10/10_2500"
2. See error

**Expected behavior**
An error message should show the user that the time inputted is invalid

**Screenshots**
![screenshot 9](https://user-images.githubusercontent.com/35787585/47906849-12322580-dec5-11e8-859d-6500486b269d.png)

**Additional context**

<hr>

**Reported by:** @kelvintankaiboon
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#321]</sub>

**Comment by luhan02** [comment]
fixed in #143
