### ISSUE TITLE
Nothing happens when listTask is executed

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#116]
**Describe the bug**
As described in the title.

**To Reproduce**
1. Try to execute listTask command

**Expected behavior**
Shows a list of all tasks from task book in the student planner according to the deadline (end DateTime).

<hr>

**Reported by:** @ladderinc
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#427]</sub>

**Comment by luhan02** [comment]
If possible, can you provide with any screenshot? coz it gives the correct output when I exexute the listTask command.
![image](https://user-images.githubusercontent.com/35754579/47929335-ad49f000-df03-11e8-8720-d75863049265.png)
![image](https://user-images.githubusercontent.com/35754579/47929346-b33fd100-df03-11e8-8f9c-6a015808acca.png)

**Comment by QzSG** [comment]
@luhan02 I think @ladderinc expects listing of tasks to be in order of task deadline which is more of a suggestion than an actual bug

**Comment by Boon-Jun** [comment]
The expected behaviour is something that I copy-pasted from your user guide. So maybe you should update your user guide accordingly to prevent further confusion?

**Comment by QzSG** [comment]
It seems that it is indeed working fine on my side too.
Running `listTasks` indeed produces a sorted lists of Tasks in accordance to their deadlines.

Hmmm

**Comment by Boon-Jun** [comment]
Sorry @luhan02 . Didnt realize the second screenshot is posted by you. Not sure if this will help, but this is the data that I have inside the application when the listTask command failed to work.

![image](https://user-images.githubusercontent.com/35420846/47948614-ef5c4b80-df6e-11e8-86e1-6fdc7a1b6e34.png)

![image](https://user-images.githubusercontent.com/35420846/47948613-e66b7a00-df6e-11e8-9a36-7706cb88fd15.png)

**Comment by luhan02** [comment]
Thanks @ladderinc for pointing out the issue, will be addressed in v1.4.

**Comment by luhan02** [comment]
fixed in #143
