### ISSUE TITLE
Error in UG for 3.7 and 3.8 examples

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#117]
**Describe the bug**
Examples show "findaddress" instead of  "findname" and  "findphone"

**To Reproduce**
1. Go to User Guide
2. Click on 3.7
3. Scroll down to "Examples"

**Expected behavior**
Replace "findaddress" with correct commands.

**Screenshots**
![screenshot 11](https://user-images.githubusercontent.com/35787585/47907404-29254780-dec6-11e8-826e-86d6e2509ab3.png)

**Additional context**

<hr>

**Reported by:** @kelvintankaiboon
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#445]</sub>

**Comment by QzSG** [comment]
Fixed in #115
