### ISSUE TITLE
Error in phone number

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#120]
**Describe the bug**
The application does not take into account spacings between phone numbers 

**To Reproduce**
1. Open application
2. add n/Betsy Crowe t/friend e/betsycrowe@example.com a/Newgate Prison p/65 8123 4567 t/criminal

**Expected behavior**
The person Betsy Crowe with tag friend and criminal, email betsycrowe@example.com, address Newgate Prison and phone number 65 8123 4567 should be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/35786203/47907502-5c67d680-dec6-11e8-9dd4-88ebdc5eef04.png)

**Additional context**

<hr>

**Reported by:** @peiying98
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#527]</sub>

**Comment by QzSG** [comment]
Inherited bug from AB4, keeping open for now
