### ISSUE TITLE
The sugggestion is of the wrong format

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#121]
**Describe the bug**
while deleting the expense, the suggested input is of the wrong format. Should be a space between the command and index.

**To Reproduce**
1. open the app
2. input the deleteExpense 
3. a suggesting box will show
4. press enter
5. the suggested input will be filled and this is of wrong format

**Expected behavior**
change only the index will be notified of wong format

**Screenshots**
![screen shot 2018-11-02 at 17 27 27](https://user-images.githubusercontent.com/34418860/47907910-2414c800-dec7-11e8-91fc-035516b7247f.png)

**Additional context**
NA

<hr>

**Reported by:** @ftywan
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#558]</sub>

**Comment by ChenSongJian** [comment]
fixed in #130
