### ISSUE TITLE
Could not update enddate of tasks with updateTask command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#124]
**Describe the bug**
End_date does not update upon execution of updateTask command

**To Reproduce**
1. Execute the following command updateTask 1 e/10/10

**Expected behavior**
End date of the task does not update.

<hr>

**Reported by:** @ladderinc
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#675]</sub>

**Comment by luhan02** [comment]
fixed in #143
