### ISSUE TITLE
Can update start date of tasks to impossible date

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#126]
**Describe the bug**
As described in title.

**To Reproduce**
1. Execute the command updateTask s/99/10

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35420846/47908455-34797280-dec8-11e8-8b19-38f04d7319f6.png)

<hr>

**Reported by:** @ladderinc
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#718]</sub>

**Comment by luhan02** [comment]
Duplicate of #110

**Comment by luhan02** [comment]
Duplicate of #110
