### ISSUE TITLE
[Project v1.1] Update About Us documentation

### ISSUE THREAD

**Issue by QzSG** [CS2113-AY1819S1-T13-1/main#25]
Pull upstream commits from `CS2113-AY1819S1-T13-1/main` **`master`** branch into your own fork **`master`**.

Checkout to any branch u like

Go to `AboutUs.adoc` 

Let's put it in alphabetical order so it's more pleasing to read through?

So `Adrian` -> `Chen Song Jian` -> `Ian` -> `Lu Han` -> `Mario`  

Update the slot for yours based on the above. 

> The photo of a team member should be doc/images/githbub_username_in_lower_case.png e.g. docs/images/akshay.png

`Project Role / Responsibilities` : If you really want some role / responsibility just add in, can always modify later.

Create a pull request to `CS2113-AY1819S1-T13-1/main` **`docs/about`** branch

Mention this issue in your pr by simply typing this in the body somewhere `#25`

I'll do pr to merge to master once all done and no conflicts

Oh right please do latest by Wednesday before 4pm (just get a nice handsome/pretty/cute/etc photo) and change your name.

**Comment by T0roloco** [comment]
I submitted my PR for #25
