### ISSUE TITLE
[Feature] Contacts v1.2

### ISSUE THREAD

**Issue by QzSG** [CS2113-AY1819S1-T13-1/main#53]

**Comment by T0roloco** [comment]
I closed the pull request that had the typo and made a new pull request. Tried to edit the pull request but wasn't sure how to do it. Sorry for the inconvenience

**Comment by T0roloco** [comment]
#52

**Comment by T0roloco** [comment]
#54

**Comment by QzSG** [comment]
> I closed the pull request that had the typo and made a new pull request. Tried to edit the pull request but wasn't sure how to do it. Sorry for the inconvenience
No worries.

When you make a pull request from your branch, essentially you can just make changes and updates to the branch, say I make a pr from `you/branch` to `org/main`, any commits i make to `you/branch` will be updated and shown on the pr.
